# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: ZENworks.Version.SemVer
PackageVersion: 2.10.15

Installers:
  - Architecture: x64
    InstallerType: msi
    InstallerUrl: https://example.com/zenworks-version-semver-2.10.15.msi
    InstallerSha256: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

ManifestType: installer
ManifestVersion: 1.10.0

